sudo: false
language: android
jdk: openjdk8
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a434c0997c2c1629fef2
    on_success: change
    on_failure: always
    on_start: never
android:
  components:
  - tools
  - platform-tools
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: b/t7EEtP6N3vt1KOXBOKjA5OQRgdeXKa4E3kraOHk324NstIgdsL+JQwiDAykdRfQ0Dceoi+YgZDj7iwCmQBlTzWsnQoEMzyqUvc8Y+SPcAU9gaqzyNvzvEuSefZIEk54RkXEOM9ZXQQTg/02Dfe87kQucIqYSd74iavAw68nDi3xvEkhsdoVZpM3IqEYwwp2llKX20D8Wj4iEwnViTfIn7bHttb2LwuehL6Z5pCgfTNH2mfrIbogbJruWqqRNxOedIvPJNWxUBOjB9I9mBDLI96UkfeRjOuq/iDHzB7PIU3M/duNfoW6Svx30Xywst7LJ+aD1v3yvgoYXJIqV0v7+ixETWWE6Yp9OK+hn5LEHFqVT0C+tXVm8Tu1tXv01ntdNHS37aBLHsAXR9K6CHrVgaGSXMcZMrdB+aSQ0MCeAfpeaT+b2zHFNvub9hS3rNOLcOORZGB+2QtOOp/biIrcdDKIvR8ZquG6coD60T9rn44a6HHEeUHnprjFq55cMiOimCyZNGkoruosHIZN+2PBYdepmLxPnqnjV4zxTA9rSOef1Yq1fOv9hWXkvOqoO6IRfAF2hs1kRnSbmuDEI+oQCq/v5GRq3b1D140Fny/1dXcuQhyhT0tDxR4F7qPFPtSJksaNL/uz1Y0wwBy9ZFXzmH6Cd+MD3GxUwsKEtxqIs0=
  - secure: JJwmkLNmU7Zs/GoIjMI0LDm4r2W/NMVziw/AMNelqE9UAHMa1jdNALs3PEutItmGvJ1lgYw/QE+w3l9/C6SfQLE8paV+3BC5bYTUA02PwaRnzUzYfJ03RHO+iJ4NwRmel5oQvo1atD3SF/xF1Eo8b/goW4YMHpZaEgKWAMu7ESclVrSE4VPmbsUDkolePzT/mAYvH6ZqmJPedQxxCUj9CQZlBsAdG53oEJK7vqfrrFCmwze+NWwbLFjgwB2NSnnV55NLrFRuB5xww7qeMxiorR8FlHodKdqpCzKfJznTxBCvZ5d0sdiq0ZxxcdHoBy3m7zT8qvFATp6cb3S5rA2hbQDrzFHbr1ZP3+75F/KwRi1+22MQywRswNsr9XcIyminYPsg018JU8HAUvm1WFbY8laeklnSaX/ebdo5uoTgJpRFVs47a+eNlRLY8FJFKvEkyQdPWwY2VkXd0PWNoIctmhMWbKImqbJQVfAi0OELfXbQrBuiblkF7MEjfAED33fhXncq+6poyTJyGolQfK8GvuHmrmVKi6j6jd2GDYlulGkY2pi9W82WF7uGUYLbcmrH2lGQBZ4h3OQAFwlQufDbbGFP98wWVQY6X12bUHaQKFNi2Ah1U1FoQhyw8omfaenmc/b57w7xIkvHjD2Kc9rhwT9fnglJYFVdA7/kJDdfp14=
  - secure: NkT1LJ0Ru3sM9OxagtpL9TbTEPBFplijamtz/z7N0GvUpOiaVwM4DU4CjAF3UJN1+SvPtyqNOTL864j7Fz8uKI30XLBy/PulKCniyv83hmFiDgr1eOjsEH+GSRie3N/di93oJUmX+aFtanVK7ykvZ5TmDROM8Rz5FLXev78IFX7eRYjYdrV09S26fP9gkN8tUlZtxlo7z77DZwJC8rXVu9z9X4GRpMWUqOzeroTKWPltAJpY2RxCnZHb/rEWOAFMo+hBqEzyoDBDgQDQhuw8NBB631Sze29/VuJNE3uAOnD6Ku8N7eVmLPG1fD+Zb1BLc/vKiqIy+4k1yNt8rYpua/hWCBAg/KRzlMN2EaxHp2i0rKTCLnjsqymZGYXA28GXETHj6XvlCgTaStCUWgVB5OSKdbQ+jmiSCUxQSD4I5e5/iEQLLNHV5OpZPyesk3Qi+WVcRmEZTXamPHEV8IcT6xctkBVsssQEQt+PK7NVTFbuaI0RxMpu/Lb2nEJuQbem9Afu+vrBUQC9m/izTR8zvrYevSd2xR8c1t/VLdJrIcnWnwo6kdWZghHnh2oSjy2ChYFCNxsum4JHLpc9srMi3Dp5vzaB24CxeuMJU1DLMaD+E5ubjTZifzGsay72IIO6aTVvMoreG8QRnNJSGSSVekaIt5V8J0EssIvKpzcwgyw=
  - secure: qDJKzzaszD14tonIko4WyldqjXuINYhuNjTy6gmfOCpg6IF7EExdGuYM1u281wm0I6nyEp0ICdJNwIlkMVT5aGCGxdtJu+sO0BSnUudLuf9RswlQMZ/U9jwbFAcXfWpEeBKjp89HBZrPCMe70mCnuOoHjs9m2G1X+AZGDkTKL7qSiokyHK290gTSUW6oBVzaxEI/0NF2sZitCAM+cSfZn72Ww2Y8atSdQt198WsNltI/rmE391aRSvG6jhssE/A7eANLb9Y0oAWTcGMrsyz/F1+YYK7Joc5/B7Ui8BtuXTnTEbkflTBSv47RaCJjBOKdLPIZf9c672UvlX98Y3TRMQHFhQOLDzuS7dTdWnif0XYB+dXRwzBti5LwNXCyo9f5QoX9EWwX4xJb8YRWr9A9pC5cIaWVaHJjzr2+QChtK3tzaN9q6qiFVPcaVWyIFR1VSB0VRkN0yS2Qn+gmPnQz0uIUwAijHE5TYoI57sDKHzu5VuPpCPrM3Lterv9OCXB1fu/VzmGuB8r2KzKiOupPgoUm2NIOs6ZtMp9Q7JhGoBgqenpa6YvqIWmDmghjsX1gtrEusNrX0FKZiNPuUub1QpRSHa+u8fAfvcDjdBzJBm9k16BeqgRkledWs+p8aDKg8QcA+Wl0BAcF9w5MZ6FNAkqVKluM5ctayTbHgSMa5CU=
  - secure: Ifb05kgFqYIaB5U2pfYohCMcBSh2KNv/NLUlyiiXGCWfnnAtcQvc+hiPDPk2ERXmzwEuQcsJfNLWrX3BBU5FJrgkHEIu+zXTlMPCbUABtrMtGHsdWMh7n48xj0jmlg6FLbjFLoXOAGv+P+bpWiDtD6kQqC8oS7ZU3OIB52lbqatomDMZesxo23Lv0MUk7Ha0hDsLZdSIfH2sy5SEBfI8uBwmkuFUZ/eeHmrtC39I+Mq9quVGueKqAXzUpQuiHhvyh78NyJTrEuPBDWmvKIjMVemFMHxyAmN3wYFRRf/qc9OZiIhxizUJTh9psvy5PpL6ye4BhxttMM1I2zemBnzO52ZYg36Oni1uUiChzsSwcTPImf4esc5GizksQN6mQeVTrWCz9BNb0nz/fJc+f8fQAMWscuJuPV/yA1eze0n0hAa8owJppSbTDqZjAtIAwmHq12X3I26ccsqLrROK8h20WbNeFCM2nWS/t/OyT+e9vuAGn9QuVOSRyhnjwjXdZR0yPrGuO778NJb0QrO8Vnmmb0bjVah3p2+NdHDTEXFCUh47rVENtGUEBndM1Ki8iZcOVsTFJ7dFsA7F+at+CPw1ijG0GTPSIwNDRoDxWspgqVWXtgvsocp0g044k5UCNUvHhboia+Rzz9+Vqj2qZZimAx+a9vnTyJ1Rb6l47dlSBoI=
