sudo: false
language: android
jdk: openjdk8
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a434c0997c2c1629fef2
    on_success: change
    on_failure: always
    on_start: never
android:
  components:
  - tools
  - platform-tools
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: nL4pNgYVyFXtu1vbgm0oLepZWRM7ehDAuvDHXZNimWTqZxrY/WAAGx1NQtEvQ2PFlqih1oWG7qWqXPuIsIa7ZOUBPkf83ktPYxc3DJ5gh9BE2sjvzwMSddSadr0gQLgCdk4OXh0mukPODKzhsTZCS9ZG3ccxyJq2diGwPktg4U+slQpnDLaOswcopdFIxQEKdNUJjCeBxctcWgnzRmQDz4bA06VGf2c6dFz3KccAygB3NHKZx7yOrzg8fzFRtNu5+KiiAik84qx0E3z3iEpdRwfp8Pik2Ptdj/eHVJ2yy58L5c8L7sJM6eEV3TvymH45qleJnSUtzMEKq9fHbjOaYf28BDP1/DxtY8jwo/KUOSFwevmUpht9q9mR2ctDKVy5qy8XZA+3zrETrULqV5tCRjfP2JC1MQLW36/BrGmW0Ry+/NxMmLluqUDy/FyFGpjL8gPpwKasz9c9/bvNxashhx7CvAuNDmxVjt7Y3gseODH0M5Yr1BnengpmgTHQiRMyqR7xGY+ACxMrkD60q9f6zHDQGzhEovFA63DPCyOrOGv5KFe0z3drd87ti5g2SiufmY75XdFZsw/8thPPzBP+NvZVQlYNJwntzwTAQ6mVz1pveTQ+tsZto69pymdzagIIyx+Wjl3t2MJiO6KWbXu0qAtroutqtytXw227OC1LoIg=
  - secure: tx5v/stZ6eMON5rW6noXs7CodNklsGG+GOG/G8QgoMiGiNDR1oYwCIKqrPKjSczx86dOYct7FPEMv242dy/vX7ZHdAWm1nlAGS0eEiNkAku2rQKQjHArPskSYmM9FcbrV7d1bk1BrKXIEHU7tNdxpv0SHIuO3Wb4HYv8g0UnovYIRDsiploSWVJxO0Fn50Q9jSG+88OFgzpLprkoXY8w3qj0H3/zOz5x3CzmB4eBBgCJqBPi+4S0O7kes3hDSTiIUtoK040xnz1+ketE5l1ybAmAtS3SQwRDVcJFEleV3TVKi+SpfGIrfD86jGWAAatuoV6PUdIoGtmvQLi+XErOHAoe69Je2lS/fK8j9XIoULPYOYal4rhmsRqtHPSfMXCUQq3iakkxsYbZLOaGnNr9OmgOKs+wuGJ66RGyanQkQ1mzFNncCWxnpIX4Tq74m5vokSSvTGdDdOPndxHFyoqBTLh/wamm8vYYGZWG/zcegLWy369z8aoiPtDYPFPzfBz8kqgruyGeKLJMeLYIgJSigFPAOPS2Ik4qS1d5j4QBELC2bie8y/tFr4cxDn7GcRRKkE3nINYeiWbHpfXt4tacpd0G5REzj8dxA0mM4BXOyK30nd0SLNorBPRHO59WMPxnRZsjBIcrB0Sh16/54PdAuuQYG+m2fitSfktUKWRy2Y0=
  - secure: O1ol7oEZG8VMZxjAWNyoekUavk2j4dJ1NgufS//KPnWzKpyeKtc0/a8xqeUC9LZKRoFEwZwoBSJk7CBxNAvDNmaUmae27IgD7LtzRY2c9hOiDMn4CzEIS+9jvz007bpuLqktTZMWMoV3P8wO13FkqFm5kBYr+NeixLoK86rP20QNUwYrsiIMtyQIrFBAk7Z2UOpwqO/ri9cow5x0S5EVaP9SiaUgd7QUWarf8WSqokW7c4e7/4Y6LDxx33YyYHkkYrdX4NltRzVwbGN7hZyUp+WCk9JhFbDATHYOaRrYyi65tuUuhBbjA//VPqhnowVTgLEJA2OpTuZ6Vaeg6vahMp9QsSrvh7mbpdwv129qYsppDG5OqddV8G/x0WFY9g4/1UKGQzwNqCDVo+rfjEjJ4tkoek7wmGkPg7tO5sFr8orM5h4FmBlQtpilcPKtyk70R4FH9kbq5o8U0hAkw08/b/urJzKx8QnpFd+awhtozTktV4fr1X5IFMRQMOMBW7mRGK4dNv3ywJxCn9DORK6g5ShfKFRd7SVS1ByFKDNS3I2qhCPHBwjmiCuBy+1liOwYfXONhgZselihA7Cgqm5y+LcLbG/EZy1bVFZFxdWOLiLTmxfwfWb3MMqiG7kUtmB7acK4Lw3peihTI50pYmoovX4BulZqUzzC3MlP04SxJSI=
  - secure: dSg7vxMSjCIKn3GDD7zoXHO0IKKE53zMUsecmm1I2ivYobCgFzDgRf6u+MdVTKHeLcokUZufkLOMzWOaK6kVWSeFEjJ/07dG+7MhiEB/VO0KRgjV1e1sYUBwWrmQRWmL/qhbp8KKYTwOgXSXxEwZsPGn8wYZ34l6cuXD3PyXkuKfrlIXAV6z+DrB3161LrneWDGfuButN5Q02SnpCVfp+5/F4hbj0eAcngIO87A22XxqP7ojkTKDlrAJzBzp9qZVnKy8xx+AZxSCJ3oG41S37cyWjpNA5P/G0UtLW/CemXdn5NXrW4g8rhQZ4Cj8BThovV+tgRUeM8WhKc9r2/9Np8X90mmM3Yqi2f+inx6gq/cWAZfKSIrnRHklYOAX21G2FHBqfmpndUaJ6KDB/xpjs/B6YxNJTL5wJk0fcW799FKZdCcrfukVhQYqrYNaPUaep29mDdE3yikGFyXDkvmU/hOoiRlAk1eqTUxYw93ZytGS0lMNKRLWHbFQnDpauXSyeZ+ktBFq2tUcO+T92+3MIjDuQLspjJN+e5yCgHzuX0kov66EDaalkuRWjPs6fmnbDqiym40vBcA/ogzyuvulHwvqPeKDZOF05ilQUDIxDe0wkfyg2rCH4alG41qgeE3HWAnDlmnND1mIGa7KTxOdBGVqNnCruPP1Pfqn1W3Xjzg=
  - secure: ay3ifLX8Y3ZlPIoKhHNnztpsZEjMOwBDfTd+MiPr/TD/74vcwDBmWpKs83mItzHy024ejGtYeNGBhDnEz9tQ78apportKMdgibp/oY7LCJxNLIRaBt5/smg9JmB1ORHwyzUIjBZPm5WN3HMdi6jsEMpK15nZ7QU0cmbwjgXdP8Su9nYX9/O/0xZK/vqBxV1uIHadAumy0N8Bw7Xfn2CLA7jScglW/YLSsXO4FxbeNxQ9FMiwklrZrxiA0152DHb04ch7AwcteTUSgfWclouJnKGwS9uJTEOjo5V44ERUSeFegvIZDUtbMLcnlKjIx8fTK4pIbTrT5hGDISiQd1kc1xRZdXlmew7B/P1f9uZf+2cG1dFhc/sMzXkbl9uSLpOZ1qqnnI/u/gY8hR0DWkkalnqFrLj/6Fwh/C1530hNxdOqZlEv/W2PtPZE3oW/ZheaYI+Cn7K8BCtbKGr2bxJIGd+35szpJIio11GUDDs5+LWuzxjCI1taEDVSjRbp6yp/B9zOq4iK0r6kWGA+SRrI05iUn1xyl95zJwZai+7xvU4RctCW5wa6ZSqFW2gVEE4swGf7PvXhEAcYocNWQU2F0QqGwLtPjKOpsDEmGQMikuaQJGT4q7cIyuwKzgWsV/3KZjO74DQaZRnYLN5v+9o4sWhGvoqJMHQKSAxB1zQTmdA=
